---
version: "3.7"

services:
  scanner:
    container_name: scanner
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/opt/scanner
    networks:
      - scanner_network

networks:
  scanner_network:
    name: scanner_network